# Generated by Django 4.1.7 on 2024-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customer_phone_number_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.FloatField(),
        ),
    ]
